import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/layout/header/HeaderComponent";
import "bootstrap/dist/css/bootstrap.min.css";
import NavbarComponent from "@/components/layout/nav/NavigationBarComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HeaderComponent />
        <main className="container mt-4 d-flex flex-row justify-content-between">
          <NavbarComponent />
          {children}
       
        </main>
      </body>
    </html>
  );
}
