import type { Metadata } from "next";
import "@/app/globals.css";
import HeaderComponent from "@/components/layout/header/HeaderComponent";
import "bootstrap/dist/css/bootstrap.min.css";
import SidebarComponent from "@/components/layout/sidebar/SideBarComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderComponent />
      <main className="mt-4 d-flex flex-column flex-md-row" >
      <SidebarComponent className="col-12 col-md-2 mb-4 mb-md-0" />
      <div className="container col-12 col-md-10">
        <div className="container">{children}</div>
      </div>
      </main>
    </>
  );
}
