import type { Metadata } from "next";
import "@/app/globals.css";
import HeaderComponent from "@/components/layout/header/HeaderComponent";
import "bootstrap/dist/css/bootstrap.min.css";
import SidebarComponent from "@/components/layout/sidebar/SideBarComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderComponent />
      <main className="container mt-4 d-flex flex-row justify-content-between">
        <SidebarComponent />
        {children}
      </main>
    </>
  );
}
